---
#
# https://www.home-assistant.io/components/homekit/
#
homekit:
  name: "Home Assistant"
  entity_config: !include_dir_merge_named ../assistants/siri
  filter:
    include_entities:
      - alarm_control_panel.home
      - binary_sensor.ring_voordeur_ding
      - climate.toon_thermostat
      - input_boolean.ikettle
      - light.group_wardrobe_maarten_paauw
      - media_player.proxy_tv
      - switch.magic_mirror
      - switch.pc
      - switch.sonoff_s20_1_relay
      - switch.sonoff_s20_2_relay
      - switch.sonoff_touch_dressing_room_relay
      # - switch.transmission
