- platform: mqtt
  name: "Sonoff Basic Fan"
  state_topic: "stat/sonoff-basic-fan/POWER1"
  command_topic: "cmnd/sonoff-basic-fan/POWER1"
  availability_topic: "tele/sonoff-basic-fan/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
