- platform: mqtt
  name: "Sonoff Basic Fan"
  state_topic: "stat/sonoff-basic-fan/POWER"
  command_topic: "cmnd/sonoff-basic-fan/POWER"
  availability_topic: "tele/sonoff-basic-fan/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  qos: 1
  retain: true
