- platform: mqtt
  name: "Sonoff Touch Dressing Room"
  state_topic: "stat/sonoff-touch-dressing-room/POWER"
  command_topic: "cmnd/sonoff-touch-dressing-room/POWER"
  availability_topic: "tele/sonoff-touch-dressing-room/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  qos: 1
  retain: true
