- platform: mqtt
  name: "Sonoff S20 Coffee Machine"
  state_topic: "stat/sonoff-s20-coffee-machine/POWER"
  command_topic: "cmnd/sonoff-s20-coffee-machine/POWER"
  availability_topic: "tele/sonoff-s20-coffee-machine/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
