- platform: mqtt
  name: "Sonoff Basic Heater"
  state_topic: "stat/sonoff-basic-heater/POWER1"
  command_topic: "cmnd/sonoff-basic-heater/POWER1"
  availability_topic: "tele/sonoff-basic-heater/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
