- alias: updater_notification_ios_iphone_8_plus_van_maarten_paauw
  initial_state: True
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    - service: notify.ios_iphone_8_plus_van_maarten_paauw
      data:
        title: "Update voor Home Assistant"
        message: "Er is een nieuwe update uit voor Home Assistant"
