---
#
# https://www.home-assistant.io/components/automation/
#
alias: faceit_game_ended
trigger:
  - platform: webhook
    webhook_id: faceit_game_ended
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.faceit
