#
# https://www.home-assistant.io/components/automation/
#
alias: sensor_brother_drum_below_20_percent
initial_state: true
trigger:
  - platform: numeric_state
    entity_id: sensor.brother_drum
    below: 20
action:
  - service: notify.maarten_paauw_and_rianne_van_der_maat
    data:
      title: Brother
      message: De drum is bijna op!
