#
# https://www.home-assistant.io/components/automation/
#
alias: dinner_planner_notify_plan_week_at_sunday_20_00
trigger:
  - platform: time
    at: "20:00:00"
condition:
  - condition: time
    weekday:
      - sun
action:
  - service: notify.maarten_paauw_and_rianne_van_der_maat
    data:
      title: Nieuwe maaltijden
      message: Tijd om voor komende week te plannen!
