- alias: input_datetime_alarm_clock_rianne_van_der_maat
  initial_state: true
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.alarm_clock_rianne_van_der_maat.attributes.timestamp | int | timestamp_custom('%H:%M', false)) }}"
  condition:
    - condition: state
      entity_id: input_boolean.alarm_clock_rianne_van_der_maat
      state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.nachtlamp_van_rianne
        transition: 300
        profile: "concentrate"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.alarm_clock_rianne_van_der_maat
    - service: notify.ios_iphone_6s_van_rianne_van_der_maat
      data:
        title: "Goedemorgen!"
        message: "Wat wil je drinken?"
        data:
          push:
            badge: 0
            category: "coffee_or_tea"
