- alias: input_datetime_alarm_clock_rianne_van_der_maat
  initial_state: true
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.alarm_clock_rianne_van_der_maat.attributes.timestamp | int | timestamp_custom('%H:%M', false)) }}"
  condition:
    - condition: state
      entity_id: input_boolean.alarm_clock_rianne_van_der_maat
      state: "on"
  action:
    - service: script.turn_on
      data:
        entity_id: script.light_turn_on_bedlamp_with_profile_morning
        variables:
          device: "nachtlamp_van_rianne"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.alarm_clock_rianne_van_der_maat
    - service: script.turn_on
      data:
        entity_id: script.notify_smartphone_ask_which_drink
        variables:
          device: "iphone_rianne_van_der_maat"
