- alias: input_datetime_alarm_clock_maarten_paauw
  initial_state: true
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.alarm_clock_maarten_paauw.attributes.timestamp | int | timestamp_custom('%H:%M', false)) }}"
  condition:
    - condition: state
      entity_id: input_boolean.alarm_clock_maarten_paauw
      state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.nachtlamp_van_maarten
        transition: 300
        profile: "morning"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.alarm_clock_maarten_paauw
    - service: notify.IPHONE_MAARTEN_PAAUW
      data:
        title: "Goedemorgen!"
        message: "Wat wil je drinken?"
        data:
          push:
            badge: 0
            category: "coffee_or_tea"
    - delay: "00:30:00"
    - service: script.turn_on
      data:
        entity_id: script.notify_maarten_paauw_seretide_diskus_taken
