- alias: input_datetime_alarm_clock_maarten_paauw_changed
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_datetime.alarm_clock_maarten_paauw
  condition:
    - condition: state
      entity_id: input_boolean.alarm_clock_maarten_paauw
      state: "off"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.alarm_clock_maarten_paauw
