- alias: ios_notification_action_input_number_seretide_diskus_decrement
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SERETIDE_DISKUS_TAKEN
  action:
    - service: script.turn_on
      data:
        entity_id: script.input_number_seretide_diskus_decrement
