- alias: ios_notification_action_coffee_or_tea_picked_coffee
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: COFFEE
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.sonoff_s20_coffee_machine
