- alias: ios_notification_action_input_number_seretide_diskus_decrement
  initial_state: True
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SERETIDE_DISKUS_TAKEN
  action:
    - service: input_number.decrement
      data:
        entity_id: input_number.seretide_diskus
