#
# https://www.home-assistant.io/components/group/
#
bathroom:
  name: Badkamer
  icon: mdi:hot-tub
  control: hidden
  entities:
    - script.input_number_seretide_diskus_decrement
    - input_number.seretide_diskus
