#
# https://www.home-assistant.io/components/group/
#
default_view:
  name: Brouwerstraat
  view: yes
  entities:
    - camera.voordeur
    - alarm_control_panel.home
    - group.climate
    - group.family
    - group.dinner_planner
