#
# https://www.home-assistant.io/components/group/
#
downstairs:
  name: Beneden
  view: yes
  entities:
    - group.bathroom
    - group.hall
    - group.kitchen
    - group.living_room
    - group.shed
    - group.staircase
    - group.restroom_downstairs
