#
# https://www.home-assistant.io/components/group/
#
upstairs:
  name: Boven
  view: yes
  entities:
    - group.bedroom
    - group.corridor
    - group.dressing_room
    - group.office
    - group.restroom_upstairs
