- alias: input_boolean_tv_off_turn_off_tv
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.tv
      to: "off"
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.tv
