dist: xenial

language: python

python:
  - 3.7.4

git:
  submodules: false

before_install:
  - cp secrets.example config/secrets.yaml

install:
  - pip install yamllint
  - pip install -I homeassistant==$(cat config/.HA_VERSION)

script:
  - yamllint .
  - hass -c config --script check_config
