dist: xenial
language: python
python:
  - 3.7.4
before_install:
  - cp secrets.example secrets.yaml
install:
  - pip install -I homeassistant==$(cat .HA_VERSION)
script:
  - hass -c . --script check_config
