homeassistant:
  name: Brouwerstraat
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: 3
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include_dir_merge_named customizations

# Apple
ios:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Map
map:

# Enables configuration UI
config:

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

# Apple TV
apple_tv: !include_dir_merge_list apple_tv

# Toon
toon:
  username: !secret toon_username
  password: !secret toon_password

automation: !include_dir_merge_list automations
group: !include_dir_merge_named groups
script: !include scripts.yaml
switch: !include_dir_merge_list switches
zone: !include_dir_merge_list zones
