homeassistant:
  name: Brouwerstraat
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: 3
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include_dir_merge_named customizations/entity
  customize_glob: !include_dir_merge_named customizations/global

# Apple
apple_tv: !include_dir_merge_list apple/apple_tv
homekit: !include apple/homekit/homekit.yaml
ios: !include apple/ios/ios.yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html

customizer:
  custom_ui: local

# Map
map:

# Mosquitto
mqtt:
  discovery: true

# Recorder
recorder:

# Enables configuration UI
config:

# Shopping list
shopping_list:

# HTTP
http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# IFTTT
ifttt:
  key: !secret ifttt_key

# Toon
toon:
  username: !secret toon_username
  password: !secret toon_password

automation: !include_dir_merge_list automations
group: !include_dir_merge_named groups
input_boolean: !include_dir_merge_named input/input_booleans
input_datetime: !include_dir_merge_named input/input_datetimes
input_number: !include_dir_merge_named input/input_numbers
input_select: !include_dir_merge_named input/input_selections
light: !include_dir_merge_list lights
media_player: !include_dir_merge_list media_players
notify: !include_dir_merge_list notifies
scene: !include_dir_merge_list scenes
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensors
shell_command: !include_dir_merge_named shell_commands
switch: !include_dir_merge_list switches
zone: !include_dir_merge_list zones
