#
# https://www.home-assistant.io/components/script/
#
media_player_sonos_one_keuken_play_chime:
  alias: media_player_sonos_one_keuken_play_chime
  sequence:
    - service: variable.set_variable
      data:
        variable: media_player_sonos_one_keuken_volume
        value_template: >-
          {{ states.media_player.sonos_one_keuken.attributes.volume_level }}
    - service: media_player.volume_set
      data:
        entity_id: media_player.sonos_one_keuken
        volume_level: 0.3
    - service: media_player.play_media
      data_template:
        entity_id: media_player.sonos_one_keuken
        media_content_id: >-
          {{ states.sensor.secret_http_base_url.state }}local/pendulum_clock/chimes_at_{{ now().strftime("%I") }}_o_clock.mp3
        media_content_type: music
    - delay: "{{ now().strftime('%l') | multiply(3) | timestamp_custom('%H:%M:%S', False) }}"
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.sonos_one_keuken
        volume_level: >-
          {{ states.variable.media_player_sonos_one_keuken_volume.state }}
