- alias: sensor_brother_toner_below_20_percent
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.brother_toner
      below: 20
  action:
    - service: notify.IPHONE_MAARTEN_PAAUW_AND_RIANNE_VAN_DER_MAAT
      data:
        title: "Brother"
        message: "De toner is bijna op!"
