- alias: sensor_sonoff_pir2_staircase_turn_off_ai_light_staircase
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.sonoff_pir2_staircase
      to: "Nee"
      for:
          seconds: 30
  action:
    - service: light.turn_off
      data:
        entity_id: light.ai_light_staircase
