- alias: sensor_sonoff_rf_bridge_1_60AD41
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.sonoff_rf_bridge_1
      to: "60AD41"
  action:
    - service: notify.iphone_maarten_paauw_and_rianne_van_der_maat
      data:
        title: "Tuindeuren open"
        message: "Bella & Sarah lopen buiten!"
