- alias: sensor_sonoff_pir2_staircase_turn_on_ai_light_staircase
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.sonoff_pir2_staircase
      to: "Ja"
  action:
    - service: light.turn_on
      data:
        entity_id: light.ai_light_staircase
        brightness: 255
        color_temp: 500
        white_value: 255
