---
#
# https://www.home-assistant.io/components/person/
#
name: rianne_van_der_maat
id: rianne_van_der_maat
user_id: !secret person_rianne_van_der_maat_user_id
device_trackers:
  - device_tracker.iphone_8_van_rianne_van_der_maat
