#
# https://www.home-assistant.io/components/automation/
#
alias: dinner_planner_today_update
trigger:
  - platform: time_pattern
    minutes: "/15"
action:
  - service: homeassistant.update_entity
    data:
      entity_id: sensor.dinner_planner_today
