- platform: rest
  name: magic_mirror
  resource: http://magicmirror.local:3000/api/v1/magic-mirror/display
  method: post
  body_on: '{"state": "true"}'
  body_off: '{"state": "false"}'
  is_on_template: "{{ value_json.state }}"
  headers:
    Content-Type: application/json
