- platform: scrape
  name: "Brother"
  resource: !secret sensor_brother_resource
  select: ".tonerremain"
  attribute: height
  value_template: '{{ (100 / 56) * (value | int) }}'
  unit_of_measurement: "%"
