- platform: rest
  name: Longfonds
  resource: !secret sensor_longfonds_resource
  value_template: >
    {% if (value_json.value | float) <= 3 %}
      Goed
    {% elif (value_json.value | float) <= 6 %}
      Matig
    {% elif (value_json.value | float) <= 8 %}
      Onvoldoende
    {% else %}
      Slecht
    {% endif %}
