- alias: theme_default_on_boot
  initial_state: True
  trigger:
    - platform: homeassistant
      event: start
  condition:
    condition: sun
    after: sunrise
    after_offset: "+1:00:00"
  action:
    - service: frontend.set_theme
      data:
        name: default
