- alias: pc_turn_off_bloom_at_shutdown
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.pc
      to: "off"
      for:
        minutes: 1
  action:
    - service: light.turn_off
      data:
        entity_id: light.bloom
