- alias: switch_pc_off_turn_off_office_lights
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.pc
      to: "off"
      for:
        minutes: 3
  action:
    - service: light.turn_off
      data:
        entity_id:
         - light.kantoor_bloom
         - light.group_office_ceiling_lights
