configuration_sensor:
  name: Sensoren
  icon: mdi:run
  control: hidden
  entities:
    - automation.sensor_sonoff_pir2_staircase_turn_off_ai_light_staircase
    - automation.sensor_sonoff_pir2_staircase_turn_on_ai_light_staircase
    - automation.sensor_brother_below_20_percent
