configuration_notification_actions:
  name: Notificaties
  icon: mdi:bell-ring
  control: hidden
  entities:
    - automation.ios_notification_action_input_number_seretide_diskus_decrement
    - automation.turn_on_ikettle_notification_action
