configuration_theme:
  name: Thema
  icon: mdi:format-paint
  control: hidden
  entities:
    - automation.theme_dark_at_sunset
    - automation.theme_default_at_sunrise
    - automation.theme_dark_on_boot
    - automation.theme_default_on_boot
