configuration:
  name: Configuratie
  view: yes
  entities:
    - group.configuration_climate
    - group.configuration_input_booleans
    - group.configuration_input_datetimes
    - group.configuration_input_selections
    - group.configuration_media_players
    - group.configuration_notification_actions
    - group.configuration_sensors
    - group.configuration_switches
    - group.configuration_themes
    - group.configuration_zones
