configuration_input_datetimes:
  name: Invoer Datum-Tijden
  icon: mdi:alarm-check
  control: hidden
  entities:
    - automation.input_datetime_alarm_clock_maarten_paauw
    - automation.input_datetime_alarm_clock_rianne_van_der_maat
