---
#
# https://www.home-assistant.io/docs/configuration/basic/
#
homeassistant:
  name: Brouwerstraat
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: 3
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include_dir_merge_named customizations/entities
  customize_glob: !include_dir_merge_named customizations/globs
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_api_password
  packages: !include_dir_named integrations
