---
#
# https://www.home-assistant.io/lovelace/views/
#
title: Boven
path: upstairs
cards:
  - type: custom:mini-graph-card
    name: Klimaat
    decimals: 1
    hour24: true
    entities:
      - entity: sensor.overloop_temperature
        name: Overloop
      - entity: sensor.toilet_boven_temperature
        name: Toilet

  - type: custom:mini-media-player
    entity: media_player.spotify
    artwork: cover
    info: scroll
    hide:
      source: true
      power: true

  - type: entities
    title: Kantoor
    show_header_toggle: false
    entities:
      - type: custom:slider-entity-row
        entity: light.group_office_ceiling_lights
        toggle: true
        hide_when_off: true
      - type: custom:slider-entity-row
        entity: light.kantoor_bloom
        toggle: true
        hide_when_off: true
      - entity: switch.sonoff_s20_1_relay
      - entity: switch.sonoff_s20_2_relay
      - entity: switch.pc

  - type: entities
    title: Slaapkamer
    show_header_toggle: false
    entities:
      - type: custom:slider-entity-row
        entity: light.group_bedroom_ceiling_lights
        toggle: true
        hide_when_off: true
      - type: custom:slider-entity-row
        entity: light.group_wardrobe_maarten_paauw
        toggle: true
        hide_when_off: true
      - type: custom:slider-entity-row
        entity: light.group_bedside_lamps
        toggle: true
        hide_when_off: true
      - type: custom:slider-entity-row
        entity: light.nachtlamp_van_maarten
        toggle: true
        hide_when_off: true
      - type: custom:slider-entity-row
        entity: light.nachtlamp_van_rianne
        toggle: true
        hide_when_off: true
      - entity: switch.magic_mirror

  - type: entities
    title: Overloop
    show_header_toggle: false
    entities:
      - type: custom:slider-entity-row
        entity: light.overloop_plafondlamp
        toggle: true
        hide_when_off: true

  - type: entities
    title: Kledingkamer
    show_header_toggle: false
    entities:
      - entity: switch.sonoff_touch_dressing_room_relay

  - type: entities
    title: Toilet
    show_header_toggle: false
    entities:
      - type: custom:slider-entity-row
        entity: light.toilet_boven_plafondlamp
        toggle: true
        hide_when_off: true
