#
# https://www.home-assistant.io/components/automation/
#
alias: homeassistant_start_get_mqtt_states
initial_state: true
trigger:
  - platform: homeassistant
    event: start
action:
  - service: mqtt.publish
    data:
      topic: "cmnd/sonoff-s20-wall-fan/POWER"
      payload: ""
  - service: mqtt.publish
    data:
      topic: "cmnd/sonoff-touch-dressing-room/POWER"
      payload: ""
