- platform: template
  sensors:
    dinner_planner_saturday:
      friendly_name: "Zaterdag"
      value_template: >-
        {% if is_state("input_select.dinner_planner_saturday", "Anders") %}
          {{ states.input_text.dinner_planner_saturday.state }}
        {% else %}
          {{ states.input_select.dinner_planner_saturday.state }}
        {% endif %}
