- platform: template
  sensors:
    dinner_planner_tuesday:
      friendly_name: "Dinsdag"
      value_template: >-
        {% if is_state("input_select.dinner_planner_tuesday", "Anders") %}
          {{ states.input_text.dinner_planner_tuesday.state }}
        {% else %}
          {{ states.input_select.dinner_planner_tuesday.state }}
        {% endif %}
