- platform: template
  sensors:
    dinner_planner_sunday:
      friendly_name: "Zondag"
      value_template: >-
        {% if is_state("input_select.dinner_planner_sunday", "Anders") %}
          {{ states.input_text.dinner_planner_sunday.state }}
        {% else %}
          {{ states.input_select.dinner_planner_sunday.state }}
        {% endif %}
