- platform: template
  sensors:
    dinner_planner_wednesday:
      friendly_name: "Woensdag"
      value_template: >-
        {% if is_state("input_select.dinner_planner_wednesday", "Anders") %}
          {{ states.input_text.dinner_planner_wednesday.state }}
        {% else %}
          {{ states.input_select.dinner_planner_wednesday.state }}
        {% endif %}
