---
#
# https://www.home-assistant.io/components/automation/
#
alias: media_player_proxy_tv_off_apple_tv_off
trigger:
  - platform: state
    entity_id: media_player.proxy_tv
    to: "off"
action:
  - service: media_player.turn_off
    data:
      entity_id: media_player.apple_tv_woonkamer
