#
# https://www.home-assistant.io/components/automation/
#
alias: media_player_proxy_tv_on_apple_tv_on
initial_state: true
trigger:
  - platform: state
    entity_id: media_player.proxy_tv
    to: "on"
action:
  - service: media_player.turn_on
    data:
      entity_id: media_player.apple_tv_woonkamer
