---
#
# https://www.home-assistant.io/components/scrape/
#
platform: scrape
name: brother_toner
resource: !secret sensor_brother_status_resource
select: ".tonerremain"
attribute: height
unit_of_measurement: "%"
value_template: >-
  {{ ((100 / 56) * (value | int)) | round(2) }}
