---
#
# https://www.home-assistant.io/components/automation/
#
alias: remind_maarten_paauw_to_take_his_medication
trigger:
  - platform: time
    at: 07:00:00
action:
  - service: script.turn_on
    data:
      entity_id: script.notify_maarten_paauw_seretide_diskus_taken
